export const BASE_SIDEBAR_SECTIONS = Object.freeze([
  {
    id: 'home',
    titleKey: 'nav.sections.home',
    items: [
      {
        id: 'dashboard',
        routeName: 'dashboard',
        icon: 'bi bi-grid-1x2-fill',
        labelKey: 'routes.dashboard',
        permissions: ['dashboard.view'],
      },
      {
        id: 'user-settings',
        routeName: 'user-settings',
        icon: 'bi bi-gear-fill',
        labelKey: 'routes.userSettings',
        permissions: ['settings.view'],
      },
      {
        id: 'notifications',
        routeName: 'notifications',
        icon: 'bi bi-bell-fill',
        labelKey: 'routes.notifications',
        permissions: ['notifications.view'],
      },
      {
        id: 'instructor-self-availability',
        routeName: 'instructor-self-availability',
        icon: 'bi bi-calendar2-week',
        labelKey: 'routes.instructorSelfAvailability',
        permissions: ['instructorPreferences.self.view'],
      },
      {
        id: 'instructor-weekly-schedule',
        routeName: 'instructor-weekly-schedule',
        icon: 'bi bi-calendar-week',
        labelKey: 'routes.instructorWeeklySchedule',
        permissions: ['instructorSchedule.self.view'],
      },
      {
        id: 'instructor-lecture-requests',
        routeName: 'instructor-lecture-requests',
        icon: 'bi bi-envelope-paper',
        labelKey: 'routes.instructorLectureRequests',
        permissions: ['instructorSchedule.apologyRequest.create'],
      },
      {
        id: 'student-weekly-schedule',
        routeName: 'student-weekly-schedule',
        icon: 'bi bi-calendar-check',
        labelKey: 'routes.studentWeeklySchedule',
        permissions: ['studentSchedule.self.view'],
      },
      {
        id: 'coordinator-weekly-schedule',
        routeName: 'coordinator-weekly-schedule',
        icon: 'bi bi-calendar3-week',
        labelKey: 'routes.coordinatorWeeklySchedule',
        permissions: ['schedule.view'],
      },
      {
        id: 'coordinator-lecture-requests',
        routeName: 'coordinator-lecture-requests',
        icon: 'bi bi-list-check',
        labelKey: 'routes.coordinatorLectureRequests',
        permissions: ['instructorSchedule.requests.review'],
      },
    ],
  },
  {
    id: 'system',
    titleKey: 'nav.sections.system',
    items: [
      {
        id: 'roles-management',
        routeName: 'roles-management',
        icon: 'bi bi-shield-lock-fill',
        labelKey: 'routes.rolesManagement',
        permissions: ['roles.view'],
      },
      {
        id: 'organization-management',
        routeName: 'organization-management',
        icon: 'bi bi-diagram-3-fill',
        labelKey: 'routes.organizationManagement',
        permissions: ['organization.view'],
      },
      {
        id: 'users-management',
        routeName: 'users-management',
        icon: 'bi bi-people-fill',
        labelKey: 'routes.usersManagement',
        permissions: ['users.view'],
      },
      {
        id: 'instructors-management',
        routeName: 'instructors-management',
        icon: 'bi bi-mortarboard-fill',
        labelKey: 'routes.instructorsManagement',
        permissions: ['instructors.view'],
      },
      {
        id: 'students-management',
        routeName: 'students-management',
        icon: 'bi bi-mortarboard',
        labelKey: 'routes.studentsManagement',
        permissions: ['students.view'],
      },
      {
        id: 'resources-management',
        routeName: 'resources-management',
        icon: 'bi bi-pc-display',
        labelKey: 'routes.resourcesManagement',
        permissions: ['resources.view'],
      },
      {
        id: 'rooms-management',
        routeName: 'rooms-management',
        icon: 'bi bi-door-open-fill',
        labelKey: 'routes.roomsManagement',
        permissions: ['rooms.view'],
      },
      {
        id: 'courses-management',
        routeName: 'courses-management',
        icon: 'bi bi-journal-richtext',
        labelKey: 'routes.coursesManagement',
        permissions: ['courses.view'],
      },
      {
        id: 'specialities-management',
        routeName: 'specialities-management',
        icon: 'bi bi-bookmarks-fill',
        labelKey: 'routes.specialitiesManagement',
        permissions: ['specialities.view'],
      },
      {
        id: 'semesters-management',
        routeName: 'semesters-management',
        icon: 'bi bi-calendar3',
        labelKey: 'routes.semestersManagement',
        permissions: ['semesters.view'],
      },
      {
        id: 'constraints-management',
        routeName: 'constraints-management',
        icon: 'bi bi-sliders',
        labelKey: 'routes.constraintsManagement',
        permissions: ['constraints.view'],
      },
      {
        id: 'audit-logs',
        routeName: 'audit-logs',
        icon: 'bi bi-journal-text',
        labelKey: 'routes.auditLogs',
        permissions: ['auditLogs.view'],
      },
    ],
  },
])
