<?php

namespace App\Http\Controllers\Api\Admin;

use App\Http\Controllers\Controller;
use App\Models\SystemBackup;
use App\Services\AuditLogger;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class AdminSystemBackupController extends Controller
{
    public function createFull(Request $request): Response
    {
        $now = now();
        $tables = collect(Schema::getTableListing())
            ->filter(fn ($name) => is_string($name) && $name !== '')
            ->values();

        $pdo = DB::connection()->getPdo();
        $sqlDump = [];
        $sqlDump[] = '-- OptiTime full system backup';
        $sqlDump[] = '-- Generated at: '.$now->toIso8601String();
        $sqlDump[] = '-- Generated by user ID: '.(string) $request->user()->id;
        $sqlDump[] = 'SET FOREIGN_KEY_CHECKS=0;';
        $sqlDump[] = '';

        $tablesCount = 0;
        $rowsCount = 0;

        foreach ($tables as $table) {
            $tablesCount++;
            $sqlDump[] = '-- --------------------------------------------------------';
            $sqlDump[] = '-- Table: `'.$table.'`';

            try {
                $createResult = DB::select('SHOW CREATE TABLE `'.$table.'`');
                if (!empty($createResult)) {
                    $row = (array) $createResult[0];
                    $createSql = (string) ($row['Create Table'] ?? '');
                    if ($createSql !== '') {
                        $sqlDump[] = 'DROP TABLE IF EXISTS `'.$table.'`;';
                        $sqlDump[] = $createSql.';';
                    }
                }
            } catch (\Throwable) {
                // Keep backup resilient for non-MySQL connections.
            }

            $tableRows = DB::table($table)->get()->map(fn ($row) => (array) $row)->all();
            if (!empty($tableRows)) {
                $columns = array_keys($tableRows[0]);
                $quotedColumns = array_map(fn ($column) => '`'.$column.'`', $columns);

                foreach ($tableRows as $tableRow) {
                    $values = [];
                    foreach ($columns as $column) {
                        $value = $tableRow[$column] ?? null;
                        if ($value === null) {
                            $values[] = 'NULL';
                            continue;
                        }
                        if (is_bool($value)) {
                            $values[] = $value ? '1' : '0';
                            continue;
                        }
                        $values[] = $pdo->quote((string) $value);
                    }

                    $sqlDump[] = 'INSERT INTO `'.$table.'` ('.implode(', ', $quotedColumns).') VALUES ('.implode(', ', $values).');';
                    $rowsCount++;
                }
            }

            $sqlDump[] = '';
        }

        $backupId = (string) Str::uuid();
        $fileName = 'optitime-full-backup-'.$now->format('Y-m-d-His').'.sql';
        $dumpContent = implode("\n", $sqlDump)."\nSET FOREIGN_KEY_CHECKS=1;\n";

        SystemBackup::query()->create([
            'id' => $backupId,
            'initiated_by_user_id' => (string) $request->user()->id,
            'file_name' => $fileName,
            'storage_path' => null,
            'backup_scope' => 'full_system',
            'status' => 'completed',
            'metadata' => [
                'tables_count' => $tablesCount,
                'rows_count' => $rowsCount,
                'payload_size_bytes' => strlen($dumpContent),
                'file_type' => 'sql',
            ],
            'created_at' => $now,
        ]);

        AuditLogger::log(
            $request->user(),
            'system_backups.create_full',
            SystemBackup::class,
            $backupId,
            ['backup_scope' => 'full_system', 'tables_count' => $tablesCount, 'rows_count' => $rowsCount],
            $request
        );

        return response($dumpContent, 200, [
            'Content-Type' => 'application/sql; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="'.$fileName.'"',
        ]);
    }
}
