const AVAILABLE_PERMISSIONS = Object.freeze([
  'dashboard.view',
  'organization.create',
  'organization.update',
  'organization.delete',
  'organization.view',
  'roles.create',
  'roles.update',
  'roles.delete',
  'roles.view',
  'users.create',
  'users.update',
  'users.delete',
  'users.view',
  'instructors.create',
  'instructors.update',
  'instructors.delete',
  'instructors.view',
  'instructorPreferences.self.view',
  'instructorPreferences.self.update',
  'instructorSchedule.self.view',
  'students.create',
  'students.update',
  'students.delete',
  'students.view',
  'studentSchedule.self.view',
  'resources.create',
  'resources.update',
  'resources.delete',
  'resources.view',
  'rooms.create',
  'rooms.update',
  'rooms.delete',
  'rooms.view',
  'users.manage',
  'students.manage',
  'courses.manage',
  'courses.create',
  'courses.update',
  'courses.delete',
  'courses.view',
  'specialities.create',
  'specialities.update',
  'specialities.delete',
  'specialities.view',
  'schedule.view',
  'schedule.update',
  'schedule.generate',
  'reports.view',
  'semesters.manage',
  'semesters.create',
  'semesters.update',
  'semesters.delete',
  'semesters.view',
  'constraints.manage',
  'constraints.view',
  'auditLogs.view',
  'settings.manage',
  'notifications.view',
  'settings.view',
  'settings.profile.update',
  'settings.security.update',
  'settings.notifications.update',
  'settings.backup.create',
])

const INITIAL_ROLES = Object.freeze([
  {
    id: 'role-admin',
    code: 'admin',
    name_ar: 'مدير النظام',
    name_en: 'System admin',
    sidebar_color: '#e63946',
    description: 'System role with full role-management access.',
    is_active: true,
    permissions: [
      'dashboard.view',
      'roles.create',
      'roles.update',
      'roles.delete',
      'roles.view',
      'settings.manage',
    ],
  },
  {
    id: 'role-coordinator',
    code: 'coordinator',
    name_ar: 'منسق الموارد',
    name_en: 'Resource coordinator',
    sidebar_color: '#4361ee',
    description: '',
    is_active: true,
    permissions: [
      'dashboard.view',
      'courses.create',
      'courses.update',
      'courses.delete',
      'courses.view',
      'semesters.create',
      'semesters.update',
      'semesters.delete',
      'semesters.view',
      'schedule.view',
      'schedule.update',
      'schedule.generate',
      'settings.view',
      'settings.profile.update',
      'settings.security.update',
      'settings.notifications.update',
      'notifications.view',
    ],
  },
  {
    id: 'role-instructor',
    code: 'instructor',
    name_ar: 'مدرس',
    name_en: 'Instructor',
    sidebar_color: '#2dc653',
    description: '',
    is_active: true,
    permissions: [
      'dashboard.view',
      'instructorPreferences.self.view',
      'instructorPreferences.self.update',
      'instructorSchedule.self.view',
      'notifications.view',
      'settings.view',
      'settings.profile.update',
      'settings.security.update',
      'settings.notifications.update',
    ],
  },
  {
    id: 'role-management',
    code: 'management',
    name_ar: 'الإدارة',
    name_en: 'Management',
    sidebar_color: '#0f766e',
    description: '',
    is_active: true,
    permissions: [
      'dashboard.view',
      'courses.view',
      'semesters.view',
      'notifications.view',
      'settings.view',
      'settings.profile.update',
      'settings.security.update',
      'settings.notifications.update',
    ],
  },
  {
    id: 'role-student',
    code: 'student',
    name_ar: 'طالب',
    name_en: 'Student',
    sidebar_color: '#f8961e',
    description: '',
    is_active: true,
    permissions: [
      'dashboard.view',
      'studentSchedule.self.view',
      'settings.view',
      'settings.profile.update',
      'settings.security.update',
      'settings.notifications.update',
    ],
  },
])

function cloneRole(role) {
  return {
    ...role,
    permissions: [...role.permissions],
  }
}

export const rolesService = {
  async getPermissionsCatalog() {
    return [...AVAILABLE_PERMISSIONS]
  },

  async getRoles() {
    return INITIAL_ROLES.map(cloneRole)
  },
}
